export const messages = {
  es: {
    hero: {
      title: "Tu Computador Se Siente Lenta Y Frustrante. Nosotros La Devolvemos A La Vida. Rápido.",
      description: "SofMaster: Tu Aliado Tecnológico para soluciones rápidas y eficientes.",
      cta1: "OBTÉN SOPORTE",
      cta2: "Ver Servicios",
    },
    services: {
      title: "Nuestros Servicios",
      description: "Soluciones tecnológicas completas para tu hogar y empresa",
      optimization_title: "Optimización de PC",
      optimization_description:
        "Devolvemos la velocidad a tu computadora eliminando archivos innecesarios y optimizando el rendimiento.",
      hardware_title: "Reparación de Hardware",
      hardware_description:
        "Diagnóstico y reparación de componentes dañados: discos duros, memoria RAM, fuentes de poder.",
      virus_title: "Eliminación de Virus",
      virus_description: "Limpieza completa de malware, virus y programas maliciosos que ralentizan tu equipo.",
      software_title: "Instalación de Software",
      software_description:
        "Instalación y configuración de programas, sistemas operativos y actualizaciones de seguridad.",
    },
    plans: {
      title: "Planes de Soporte",
      description: "Elige el plan que mejor se adapte a tus necesidades",
      tab_companies: "Empresas",
      tab_home: "Hogar",
      basic_title: "Básico",
      basic_price: "Consultar",
      basic_description: "Ideal para pequeñas empresas",
      basic_features: [
        "Soporte remoto",
        "Horario laboral",
        "Tiempo de respuesta: 24h",
        "5 incidentes al mes",
        "Mantenimiento preventivo trimestral",
      ],
      professional_title: "Profesional",
      professional_price: "Cotización",
      professional_description: "Para empresas en crecimiento",
      professional_features: [
        "Soporte remoto y presencial",
        "Horario extendido",
        "Tiempo de respuesta: 8h",
        "Incidentes ilimitados",
        "Mantenimiento preventivo mensual",
      ],
      premium_title: "Premium",
      premium_price: "Personalizado",
      premium_description: "Soporte completo 24/7",
      premium_features: [
        "Soporte prioritario",
        "Disponibilidad 24/7",
        "Tiempo de respuesta: 2h",
        "Gestor de cuenta dedicado",
        "Auditoría de seguridad incluida",
      ],
      home_repair_title: "Reparación / Cambio de Piezas",
      home_repair_price: "$75 - $95 USD",
      home_repair_description:
        "Cambiamos componentes dañados con instalación profesional y garantía de compatibilidad. Asesoría incluida para elegir la mejor pieza.",
      home_repair_features: [
        "Instalación profesional del componente",
        "Pruebas de funcionamiento y compatibilidad",
        "Asesoría en la compra de la mejor pieza para tu presupuesto",
        "Mano de obra + costo de la pieza",
      ],
      home_diagnosis_title: "Diagnóstico Completo",
      home_diagnosis_price: "$50 USD",
      home_diagnosis_description:
        "Evaluación completa de tu equipo para identificar problemas exactos. Reporte detallado y presupuesto preciso incluidos.",
      home_diagnosis_features: [
        "Revisión de componentes físicos",
        "Escaneo de sistema operativo y software",
        "Presupuesto detallado para la solución",
        "Costo se abona al total si decides reparar con nosotros",
      ],
      home_virus_title: "Eliminación de Virus y Malware",
      home_virus_price: "$99 - $149 USD",
      home_virus_description:
        "Eliminamos virus, malware y amenazas que ralentizan tu PC. Recupera velocidad y protege tu información personal.",
      home_virus_features: [
        "Escaneo profundo con múltiples herramientas",
        "Limpieza de registro y archivos maliciosos",
        "Consejos para prevenir futuras infecciones",
        "Protección de tu privacidad",
      ],
      home_format_title: "Formateo e Instalación de Sistema Operativo",
      home_format_price: "$129 - $199 USD",
      home_format_description:
        "Instalación limpia de Windows o macOS para máximo rendimiento. Respaldo de archivos y software esencial incluidos.",
      home_format_features: [
        "Instalación limpia del Sistema Operativo",
        "Instalación de drivers y actualizaciones",
        "Software esencial (navegador, antivirus básico)",
        "Respaldo seguro de documentos y archivos (Plan Completo)",
      ],
      home_assembly_title: "Armado de PC Gamer / Profesional",
      home_assembly_price: "$99 - $149 USD",
      home_assembly_description:
        "Construimos tu PC ideal para gaming o trabajo profesional. Asesoría, ensamblaje experto y pruebas de rendimiento incluidas.",
      home_assembly_features: [
        "Asesoría en la selección de componentes",
        "Ensamblaje profesional y gestión de cables",
        "Instalación de sistema operativo y drivers",
        "Pruebas de rendimiento (Benchmarking)",
      ],
    },
    on_demand: {
      title: "Soporte On Demand",
      description: "¿Necesitas ayuda puntual? Contrata soporte por horas y paga solo por lo que necesitas.",
      feature1: "Sin contratos a largo plazo",
      feature2: "Técnicos certificados",
      feature3: "Disponibilidad inmediata",
      feature4: "Soporte remoto o presencial",
      cta: "Contratar Ahora",
      card_title: "Tarifas por Hora",
      card_description: "Precios transparentes sin sorpresas",
      remote_support: "Soporte Remoto",
      on_site_support: "Soporte Presencial",
      specialized_services: "Servicios Especializados",
      footer_text: "Tiempo mínimo de facturación: 1 hora. Después se factura por incrementos de 30 minutos.",
    },
    why_choose_us: {
      title: "¿Por qué elegir SofMaster?",
      description: "Somos expertos en devolver la vida a tus dispositivos",
      feature1_title: "Respuesta Rápida",
      feature1_description: "Atendemos tus problemas tecnológicos en tiempo récord para minimizar interrupciones.",
      feature2_title: "Técnicos Certificados",
      feature2_description: "Nuestro equipo cuenta con certificaciones y años de experiencia en el sector.",
      feature3_title: "Soluciones Permanentes",
      feature3_description: "No solo arreglamos el problema, identificamos y corregimos la causa raíz.",
      feature4_title: "Soporte Multidispositivo",
      feature4_description: "Atendemos computadoras, servidores, redes, y otros dispositivos.",
      feature5_title: "Infraestructura Empresarial",
      feature5_description: "Soluciones escalables para empresas de todos los tamaños.",
      feature6_title: "Mantenimiento Preventivo",
      feature6_description: "Evitamos problemas antes de que ocurran con revisiones programadas.",
    },
    testimonials: {
      title: "Lo que dicen nuestros clientes",
      description: "Miles de clientes confían en nuestro servicio de soporte técnico",
      testimonial1_content:
        "La eficiencia de SofMaster es inigualable. Su soporte remoto nos salvó de varias caídas críticas, minimizando el tiempo de inactividad. Su equipo es proactivo y altamente capacitado.",
      testimonial1_name: "Carlos Rodríguez",
      testimonial1_role: "Gerente de Operaciones",
      testimonial1_company: "Empresa ABC",
      testimonial2_content:
        "Mi laptop estaba lentísima y llena de virus. SofMaster la dejó como nueva en cuestión de horas. El técnico fue súper amable y me explicó todo con paciencia. ¡Totalmente recomendado!",
      testimonial2_name: "María González",
      testimonial2_role: "Propietaria",
      testimonial2_company: "Hogar Conectado",
      testimonial3_content:
        "El plan de soporte por horas es perfecto para nuestra startup. Nos da la flexibilidad de tener expertos a demanda sin el costo de un empleado a tiempo completo. Su rapidez y conocimiento técnico son impresionantes.",
      testimonial3_name: "Juan Pérez",
      testimonial3_role: "Director de IT",
      testimonial3_company: "Startup XYZ",
    },
    contact: {
      title: "Agenda tu Asesoría",
      description: "Completa el formulario y un especialista se pondrá en contacto contigo",
      response_title: "Respuesta Rápida",
      response_text: "Te contactaremos en menos de 2 horas para agendar tu asesoría o soporte técnico.",
      phone_title: "Línea Directa",
      phone_number: "800-123-4567",
      email_title: "Correo Electrónico",
      email_address: "soporte@sofmaster.com",
      form_title: "Solicita una asesoría",
      form_description: "Completa el formulario y te contactaremos a la brevedad",
      form_name_label: "Nombre",
      form_name_placeholder: "Tu nombre completo",
      form_email_label: "Correo electrónico",
      form_email_placeholder: "correo@ejemplo.com",
      form_phone_label: "Teléfono",
      form_phone_placeholder: "Tu número de teléfono",
      form_service_type_label: "Tipo de servicio",
      form_service_type_home: "Soporte para Hogar",
      form_service_type_business: "Soporte para Empresa",
      form_service_type_on_demand: "Soporte por Horas",
      form_urgency_label: "Urgencia",
      form_urgency_low: "Baja - En los próximos días",
      form_urgency_normal: "Normal - En las próximas 24 horas",
      form_urgency_high: "Alta - Lo antes posible",
      form_message_label: "Describe tu problema",
      form_message_placeholder: "Cuéntanos brevemente qué necesitas...",
      form_submit_button: "OBTÉN SOPORTE",
      form_submitting: "Enviando...",
      toast_title: "Solicitud enviada",
      toast_description: "Un especialista se pondrá en contacto contigo pronto.",
    },
    footer: {
      company_description: "Tu Aliado Tecnológico. Soluciones rápidas y eficientes para tu hogar y empresa.",
      services_heading: "Servicios",
      services_opt: "Optimización de PC",
      services_rec: "Recuperación de Datos",
      services_ondemand: "Soporte por Horas",
      services_security: "Seguridad Digital",
      company_heading: "Empresa",
      // Removed: company_about: "Sobre Nosotros",
      // Removed: company_team: "Nuestro Equipo",
      company_testimonials: "Testimonios",
      // Removed: company_blog: "Blog",
      contact_heading: "Contacto",
      copyright: "Todos los derechos reservados.",
      terms: "Términos de Servicio",
      privacy: "Política de Privacidad",
    },
    navbar: {
      home: "Inicio",
      services: "Servicios",
      companies: "Empresas",
      contact: "Contactos",
      get_support: "OBTÉN SOPORTE",
      toggle_menu: "Toggle Menu",
      language_button: "English",
    },
    buttons: {
      request_service: "SOLICITAR SERVICIO",
      hire: "Contratar",
    },
  },
  en: {
    hero: {
      title: "Is Your Computer Slow and Frustrating? We Bring It Back to Life. Fast.",
      description: "SofMaster: Your Technology Ally for fast and efficient solutions.",
      cta1: "GET SUPPORT",
      cta2: "View Services",
    },
    services: {
      title: "Our Services",
      description: "Complete technology solutions for your home and business",
      optimization_title: "PC Optimization",
      optimization_description:
        "We restore your computer's speed by removing unnecessary files and optimizing performance.",
      hardware_title: "Hardware Repair",
      hardware_description: "Diagnosis and repair of damaged components: hard drives, RAM, power supplies.",
      virus_title: "Virus Removal",
      virus_description: "Complete cleanup of malware, viruses, and malicious programs that slow down your equipment.",
      software_title: "Software Installation",
      software_description: "Installation and configuration of programs, operating systems, and security updates.",
    },
    plans: {
      title: "Support Plans",
      description: "Choose the plan that best suits your needs",
      tab_companies: "Businesses",
      tab_home: "Home",
      basic_title: "Basic",
      basic_price: "Inquire",
      basic_description: "Ideal for small businesses",
      basic_features: [
        "Remote support",
        "Business hours",
        "Response time: 24h",
        "5 incidents per month",
        "Quarterly preventive maintenance",
      ],
      professional_title: "Professional",
      professional_price: "Quote",
      professional_description: "For growing businesses",
      professional_features: [
        "Remote and on-site support",
        "Extended hours",
        "Response time: 8h",
        "Unlimited incidents",
        "Monthly preventive maintenance",
      ],
      premium_title: "Premium",
      premium_price: "Custom",
      premium_description: "Comprehensive 24/7 support",
      premium_features: [
        "Priority support",
        "24/7 availability",
        "Response time: 2h",
        "Dedicated account manager",
        "Security audit included",
      ],
      home_repair_title: "Repair / Parts Replacement",
      home_repair_price: "$75 - $95 USD",
      home_repair_description:
        "We replace damaged components with professional installation and compatibility guarantee. Advice included to choose the best part.",
      home_repair_features: [
        "Professional component installation",
        "Functionality and compatibility tests",
        "Advice on purchasing the best part for your budget",
        "Labor + cost of part",
      ],
      home_diagnosis_title: "Complete Diagnosis",
      home_diagnosis_price: "$50 USD",
      home_diagnosis_description:
        "Comprehensive evaluation of your equipment to identify exact problems. Detailed report and precise budget included.",
      home_diagnosis_features: [
        "Physical component review",
        "Operating system and software scan",
        "Detailed budget for the solution",
        "Cost is credited to total if you decide to repair with us",
      ],
      home_virus_title: "Virus and Malware Removal",
      home_virus_price: "$99 - $149 USD",
      home_virus_description:
        "We eliminate viruses, malware, and threats that slow down your PC. Regain speed and protect your personal information.",
      home_virus_features: [
        "Deep scan with multiple tools",
        "Registry and malicious file cleanup",
        "Tips to prevent future infections",
        "Protection of your privacy",
      ],
      home_format_title: "Operating System Formatting and Installation",
      home_format_price: "$129 - $199 USD",
      home_format_description:
        "Clean installation of Windows or macOS for maximum performance. File backup and essential software included.",
      home_format_features: [
        "Clean OS installation",
        "Driver and update installation",
        "Essential software (browser, basic antivirus)",
        "Secure document and file backup (Complete Plan)",
      ],
      home_assembly_title: "Gaming / Professional PC Assembly",
      home_assembly_price: "$99 - $149 USD",
      home_assembly_description: `We build your ideal PC for high-end gaming or professional work. Consulting, expert assembly, and performance tests included.`,
      home_assembly_features: [
        "Component selection advice",
        `Professional assembly and cable management`,
        "OS and driver installation",
        `Performance testing (Benchmarking)`,
      ],
    },
    on_demand: {
      title: `On-Demand Support`,
      description: `Need specific help? Hire hourly support and pay only for what you need.`,
      feature1: `No long-term contracts`,
      feature2: "Certified technicians",
      feature3: `Immediate availability`,
      feature4: "Remote or on-site support",
      cta: `Hire Now`,
      card_title: `Hourly Rates`,
      card_description: `Transparent pricing with no surprises`,
      remote_support: `Remote Support`,
      on_site_support: "On-site Support",
      specialized_services: "Specialized Services",
      footer_text: `Minimum billing time: 1 hour. Thereafter billed in 30-minute increments.`,
    },
    why_choose_us: {
      title: "Why Choose SofMaster?",
      description: `We are experts in bringing your devices back to life`,
      feature1_title: "Fast Response",
      feature1_description: `We address your tech issues in record time to minimize interruptions.`,
      feature2_title: `Certified Technicians`,
      feature2_description: `Our team holds certifications and years of industry experience.`,
      feature3_title: `Permanent Solutions`,
      feature3_description: "We don't just fix the problem; we identify and correct the root cause.",
      feature4_title: "Multi-device Support",
      feature4_description: "We support computers, servers, networks, and other devices.",
      feature5_title: "Enterprise Infrastructure",
      feature5_description: "Scalable solutions for businesses of all sizes.",
      feature6_title: "Preventive Maintenance",
      feature6_description: "We prevent problems before they occur with scheduled reviews.",
    },
    testimonials: {
      title: "What Our Clients Say",
      description: "Thousands of clients trust our technical support service",
      testimonial1_content:
        "SofMaster's efficiency is unmatched. Their remote support saved us from several critical outages, minimizing downtime. Their team is proactive and highly skilled.",
      testimonial1_name: "Carlos Rodríguez",
      testimonial1_role: "Operations Manager",
      testimonial1_company: "ABC Company",
      testimonial2_content:
        "My laptop was extremely slow and full of viruses. SofMaster made it like new in a matter of hours. The technician was super friendly and patiently explained everything to me. Highly recommended!",
      testimonial2_name: "María González",
      testimonial2_role: "Homeowner",
      testimonial2_company: "Connected Home",
      testimonial3_content:
        "The hourly support plan is perfect for our startup. It gives us the flexibility to have experts on demand without the cost of a full-time employee. Their speed and technical knowledge are impressive.",
      testimonial3_name: "Juan Pérez",
      testimonial3_role: "IT Director",
      testimonial3_company: "XYZ Startup",
    },
    contact: {
      title: "Schedule Your Consultation",
      description: "Fill out the form and a specialist will contact you shortly",
      response_title: "Fast Response",
      response_text: "We will contact you in less than 2 hours to schedule your consultation or technical support.",
      phone_title: "Direct Line",
      phone_number: "800-123-4567",
      email_title: "Email",
      email_address: "support@sofmaster.com",
      form_title: "Request a consultation",
      form_description: "Fill out the form and we will contact you shortly",
      form_name_label: "Name",
      form_name_placeholder: "Your full name",
      form_email_label: "Email",
      form_email_placeholder: "email@example.com",
      form_phone_label: "Phone",
      form_phone_placeholder: "Your phone number",
      form_service_type_label: "Service type",
      form_service_type_home: "Home Support",
      form_service_type_business: "Business Support",
      form_service_type_on_demand: "Hourly Support",
      form_urgency_label: "Urgency",
      form_urgency_low: "Low - In the next few days",
      form_urgency_normal: "Normal - In the next 24 hours",
      form_urgency_high: "High - As soon as possible",
      form_message_label: "Describe your problem",
      form_message_placeholder: "Tell us briefly what you need...",
      form_submit_button: "GET SUPPORT",
      form_submitting: "Submitting...",
      toast_title: "Request sent",
      toast_description: "A specialist will contact you shortly.",
    },
    footer: {
      company_description: "Your Technology Ally. Fast and efficient solutions for your home and business.",
      services_heading: "Services",
      services_opt: "PC Optimization",
      services_rec: "Data Recovery",
      services_ondemand: "Hourly Support",
      services_security: "Digital Security",
      company_heading: "Company",
      // Removed: company_about: "About Us",
      // Removed: company_team: "Our Team",
      company_testimonials: "Testimonials",
      // Removed: company_blog: "Blog",
      contact_heading: "Contact",
      copyright: "All rights reserved.",
      terms: "Terms of Service",
      privacy: "Privacy Policy",
    },
    navbar: {
      home: "Home",
      services: "Services",
      companies: "Businesses",
      contact: "Contact",
      get_support: "GET SUPPORT",
      toggle_menu: "Toggle Menu",
      language_button: "Español",
    },
    buttons: {
      request_service: "REQUEST SERVICE",
      hire: "Hire",
    },
  },
}

export type Language = "es" | "en"
export type Messages = typeof messages.es
